// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: scheduler.proto
#ifndef GRPC_scheduler_2eproto__INCLUDED
#define GRPC_scheduler_2eproto__INCLUDED

#include "scheduler.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

class Schedule GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::Pair>> GetSchedule(::grpc::ClientContext* context, const ::Data& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::Pair>>(GetScheduleRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::Pair>> AsyncGetSchedule(::grpc::ClientContext* context, const ::Data& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::Pair>>(AsyncGetScheduleRaw(context, request, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderInterface< ::Pair>* GetScheduleRaw(::grpc::ClientContext* context, const ::Data& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::Pair>* AsyncGetScheduleRaw(::grpc::ClientContext* context, const ::Data& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::Pair>> GetSchedule(::grpc::ClientContext* context, const ::Data& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::Pair>>(GetScheduleRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::Pair>> AsyncGetSchedule(::grpc::ClientContext* context, const ::Data& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::Pair>>(AsyncGetScheduleRaw(context, request, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReader< ::Pair>* GetScheduleRaw(::grpc::ClientContext* context, const ::Data& request) GRPC_OVERRIDE;
    ::grpc::ClientAsyncReader< ::Pair>* AsyncGetScheduleRaw(::grpc::ClientContext* context, const ::Data& request, ::grpc::CompletionQueue* cq, void* tag) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_GetSchedule_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetSchedule(::grpc::ServerContext* context, const ::Data* request, ::grpc::ServerWriter< ::Pair>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetSchedule : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetSchedule() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetSchedule() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSchedule(::grpc::ServerContext* context, const ::Data* request, ::grpc::ServerWriter< ::Pair>* writer) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetSchedule(::grpc::ServerContext* context, ::Data* request, ::grpc::ServerAsyncWriter< ::Pair>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetSchedule<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_GetSchedule : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetSchedule() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetSchedule() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetSchedule(::grpc::ServerContext* context, const ::Data* request, ::grpc::ServerWriter< ::Pair>* writer) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};


#endif  // GRPC_scheduler_2eproto__INCLUDED
